version: '2'

volumes:
    redisdata:

services:
    server:
        build:
            context: ./
            dockerfile: Dockerfile
        expose:
            - 5000
        ports:
            - "127.0.0.1:80:5000"
        links:
            - redis


    redis:
        image: docker.amigocloud.com/redis:latest
        volumes:
            - "redisdata:/data"
        expose:
            - "6379"
        hostname: redis
        restart: "on-failure"
